/**
 * ESLint flat config for State of Britain.
 * Targets browser-based D3 / vanilla JS code.
 */
export default [
  {
    files: ["shared/**/*.js"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        IntersectionObserver: "readonly",
        AbortController: "readonly",
        fetch: "readonly",
        Promise: "readonly",
        d3: "readonly",
        updateChart: "readonly",
        sessionStorage: "readonly",
        performance: "readonly",
        requestIdleCallback: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "off",
      "no-undef": "error",
      "no-redeclare": "off",
      "eqeqeq": ["error", "always"],
      "no-implicit-globals": "off",
      "no-var": "off",
      "prefer-const": "off",
      "no-console": "warn",
      "curly": ["warn", "multi-line"],
    },
  },
  {
    files: ["pages/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        IntersectionObserver: "readonly",
        AbortController: "readonly",
        fetch: "readonly",
        Promise: "readonly",
        d3: "readonly",
        MouseEvent: "readonly",
        // Shared globals from utils.js
        SOB_COLORS: "readonly",
        SOB_DURATION: "readonly",
        SOB_MOBILE: "readonly",
        sobShowTooltip: "readonly",
        sobHideTooltip: "readonly",
        sobIsMobile: "readonly",
        sobChartDims: "readonly",
        sobDebounce: "readonly",
        sobShowError: "readonly",
        sobRevealContent: "readonly",
        sobSetupScrollObserver: "readonly",
        sobFetchJSON: "readonly",
        sobInstallErrorHandler: "readonly",
        sobCheckD3: "readonly",
        sobFmtPct: "readonly",
        sobFmtBnShort: "readonly",
        sobFmt: "readonly",
        sobFmtComma: "readonly",
        sobCreateChart: "readonly",
        sobAddHoverOverlay: "readonly",
        sobAddHoverLine: "readonly",
        sobSanitizeHTML: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "off",
      "no-undef": "error",
      "no-redeclare": "off",
      "eqeqeq": ["error", "always"],
      "no-implicit-globals": "off",
      "no-var": "off",
      "prefer-const": "off",
      "no-console": "warn",
      "curly": ["warn", "multi-line"],
    },
  },
  {
    files: ["tests/**/*.js", "tests/**/*.cjs"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "commonjs",
      globals: {
        require: "readonly",
        module: "readonly",
        process: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        __dirname: "readonly",
        describe: "readonly",
        it: "readonly",
        expect: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        document: "readonly",
        window: "readonly",
        fetch: "readonly",
        Promise: "readonly",
        global: "readonly",
        // Shared sob* globals from utils.js
        SOB_COLORS: "readonly",
        SOB_DURATION: "readonly",
        SOB_MOBILE: "readonly",
        sobShowTooltip: "readonly",
        sobHideTooltip: "readonly",
        sobIsMobile: "readonly",
        sobChartDims: "readonly",
        sobDebounce: "readonly",
        sobShowError: "readonly",
        sobRevealContent: "readonly",
        sobSetupScrollObserver: "readonly",
        sobFetchJSON: "readonly",
        sobInstallErrorHandler: "readonly",
        sobCheckD3: "readonly",
        sobSanitizeHTML: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-console": "off",
    },
  },
];
